### ISSUE TITLE
BUG When GET request has query params

### ISSUE THREAD

**Issue by sarathchand09** [potapovDim/mock-backend-rest#2]
lets say there are multiple calls to same rest with differnt query params like 
/abc/test?name='sarath'
/abc/test?name='valluri'&type='good'
here we are not getting response for both the requests, even though we mocked them correctly:
its a bug in the code 
i fixed it and suggest you to add the below solution and release a new version soon 
in index.js file - inside formResponse method please change the elseif as below
 else if (handler.method == method && handler.path == pathname &&( !query || handler.requestQuery == query ))

i added this extra condition ( !query || handler.requestQuery == query ) which checks if there are queryparms sent then this should also be matched with requestquery in case of multiple requests.

other conditions can also be added but upto you guys.

**Comment by potapovDim** [comment]
@sarathchand09 Thanks for your update, right now this library was refactored and moved to new approach, query implementation will be next step 

Regards, Dmytro
