### ISSUE TITLE
It would be nice if it's posible set a host domain instead "localhost" like "0.0.0.0"

### ISSUE THREAD

**Issue by xergioalex** [potapovDim/mock-backend-rest#4]
This package is amazing, and is will be great if i can define another host like **0.0.0.0**, it's necesary to setup the fake api through a docker container.

```
const model = {
  host: '0.0.0.0',
  port: 9090,
  api: [{
    method: "GET",
    path: "/",
    response: "Hello world"
  }]
}
```

**Comment by potapovDim** [comment]
@xergioalex Hey, big thanks, ok it can be done

**Comment by potapovDim** [comment]
@xergioalex Done, u can use host now, thanks
