### ISSUE TITLE
request_body_equal_partly_equal option 

### ISSUE THREAD

**Issue by sergiigorbatiuk-usc** [potapovDim/mock-backend-rest#8]
We have request_body_equal which compare all the properties in the body, would be nice to have request_body_equal_partly_equal property which will work next way - if one or few properties in the expected body are present in the actual body object - than we can return success request

**Comment by potapovDim** [comment]
@sergiigorbatiuk-usc thanks for your issue, new features are added, examples are in spec and readme files.
https://github.com/potapovDim/json-fake-server/blob/master/specs/body_equal.partial_expected.spec.js
https://github.com/potapovDim/json-fake-server/blob/master/specs/body_equal.partial_request.spec.js
